seats/urls.py
from django.urls import path

from .views import BookSeatView


urlpatterns = [path("book/", BookSeatView.as_view(), name="book")]

ticket_booking/urls.py
from django.contrib import admin
from django.urls import path, include

from seats.views import IndexView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("seats/", include(("seats.urls", "seats"), namespace="seats")),
    path("", IndexView.as_view(), name="index"),
]

seats/models.py
from django.db import models, transaction
from django.contrib.auth.models import User


class Seat(models.Model):
    """
    Database model for seats
    """

    BOOKED = "booked"
    AVAILABLE = "available"

    booked_by = models.ForeignKey(
        User, related_name="seats", on_delete=models.SET_NULL, null=True, blank=True
    )
    booked_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=25,
        choices=[(BOOKED, BOOKED), (AVAILABLE, AVAILABLE)],
        default=AVAILABLE,
    )
    version = models.BigIntegerField(default=0)

    def __str__(self):
        """
        Formats display name for seat
        :return: string - seat's representation
        """
        return "Seat {} ({})".format(self.id, self.status)

    @transaction.atomic
    def book_seat(self, user):
        """
        Books seats selected by user while handling concurrent booking using optimistic lock in
        :param user: user instance booking the seat
        :return: Boolean - Indicating whether the booking was successful
        """
        current_version = self.version
        updated_rows = Seat.objects.filter(
            id=self.id, status=self.AVAILABLE, version=current_version
        ).update(booked_by=user, status=self.BOOKED, version=current_version + 1)
        return updated_rows > 0

    def clear_seat(self):
        """
        Clear the booked seats
        :return:
        """
        self.status = self.AVAILABLE
        self.save()

seats/forms.py
from django import forms


class TicketForm(forms.Form):
    """
    Form to validate ticket form submitted by UI
    """

    email = forms.EmailField(max_length=255)
    name = forms.CharField(max_length=255)
    seat = forms.CharField(max_length=10)

seats/views.py
from django.views import View
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.contrib import messages

from .models import Seat
from .utils import get_user, send_booking_email
from .forms import TicketForm


class IndexView(TemplateView):
    """
    Renders the home page for the app.
    """

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        return {"seats": Seat.objects.all().order_by("id")}


class BookSeatView(View):
    """
    Handles ticket booking for users.
    """

    def post(self, request):
        home_url = reverse("index")
        form = TicketForm(request.POST)

        # render error if form parameters are not correct
        if not form.is_valid():
            messages.error(request, "Invalid booking data.")
            return HttpResponseRedirect(home_url)

        email = form.cleaned_data["email"]
        first_name = form.cleaned_data["name"]
        seat_id = form.cleaned_data["seat"]
        user = get_user(email, first_name)

        # If user has already booked seat then throw error
        if user.seats.count() > 0:
            messages.error(request, "You can book only one seat.")
            return HttpResponseRedirect(home_url)

        # Try to book seat
        seat = Seat.objects.get(id=seat_id)
        if seat.book_seat(user):
            # TODO: move this to background job
            seat.refresh_from_db()
            send_booking_email(seat)
            messages.success(request, "Your seat has been successfully booked.")
            return HttpResponseRedirect(home_url)
        else:
            # Booking failed as some other booked it concurrently
            messages.error(request, "This seat is no longer available.")
            return HttpResponseRedirect(home_url)

seats/templates/index.html
{% load static %}
<html>
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Seat Booking</title>
</head>

<body class="grey">

    <nav>
        <div class="nav-wrapper grey darken-4">
            <a href="/" class="brand-logo "><i class="material-icons">cloud</i>Ticket Booking</a>
        </div>
        <div class="row">
            <div class="col m8 l8 s12">
                <div class="row">

                    <div class="col s12 m12">
                        <div class="card">
                            <div class="card-content black-text">
                                {% for msg in messages %}
                                    {% if 'error' in msg.tags %}
                                    <div class="alert alert-danger" align="center">{{msg}}</div>
                                    {% else %}
                                    <div class="alert" align="center">{{msg}}</div>
                                    {% endif %}
                                {% endfor %}
                                <div class="row">
                                    {% for seat in seats %}
                                        <div class="col m3 s3 l3">
                                            <div class="row">

                                                <div align="center" class="col m12 s12 l12">
                                                    <i id="{{seat.id}}"
                                               class="material-icons seat {{seat.status}}">
                                                event_seat
                                            </i>
                                                </div>
                                            </div>
                                            
                                        </div>
                                    {% endfor %}
                                </div>

                            </div>
                            <div class="card-action remove-padding black-text">
                                <div class="row" align="center">
                                    <div class="col m4 s4 l4">
                                        <font color="green">
                                            <i class="large material-icons legend-icon">event_seat</i>  Available
                                        </font>
                                    </div>
                                    <div class="col m4 s4 l4">
                                        <font color="grey">
                                            <i class="large material-icons legend-icon">event_seat</i>  Booked
                                        </font>
                                    </div>
                                    <div class="col m4 s4 l4">
                                        <font color="purple">
                                            <i class="large material-icons legend-icon">event_seat</i>  Selected
                                        </font>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col m4 l4 s12">
                <div class="row">
                    <div class="col s12 m12">
                        <div class="card">
                            <div class="card-content no-bottom-padding">
                                <div class="row">
                                    <form id="ticketForm" method="post" action="{% url 'seats:book' %}">
                                        {% csrf_token %}
                                        <input type="text" name="name" placeholder="Name" required>
                                        <input type="email" name="email" placeholder="Email" required>
                                        <input type="hidden" id="seatId" name="seat" required>
                                        <div align="center">
                                            <button type="submit" class="waves-effect waves-light btn">Book Seat</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!--JavaScript at end of body for optimized loading-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>